package by.epamtc.enrollmentsystem.controller.action;

public enum CommandType {
    SIGN_UP,
    AUTHORIZATION,
    LOGOUT,
    UPDATE_INFO,
    UPDATE_STUDYING_INFO,
    GET_USER_PROFILES,
    PRELOAD_WELCOMEPAGE,
    PRELOAD_FACULTIES_PAGE,
    PRELOAD_FACULTIES,
    PRELOAD_ABOUTUS_PAGE,
    PRELOAD_ADMIN_PAGE,
    PRELOAD_USERINFO_PAGE,
    PRELOAD_USER_POPUP,
    PRELOAD_SELECTED_FACULTIES,
    PRELOAD_FACILITIES_TAB,
    CHANGE_LANGUAGE,
    UPDATE_ENROLLMENT_STATUS,
    START_ENROLLMENT,
    DELETE_USER,
    EMPTY
}
